### ISSUE TITLE
Caught panic when input 'kyanos watch ssh'

### ISSUE THREAD

**Issue by 760985933** [hengyoush/kyanos#157]
```
[root@localhost home]# uname -a
Linux localhost.localdomain 3.10.0-1160.59.1.el7.x86_64 #1 SMP Wed Feb 23 16:47:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost home]# ./kyanos watch ssh
                                                
  ⣯ 🦜 Kyanos Loading...                        
                                                                                           
  Kyanos exited.                                    
                                                    
  🍆 Attached base eBPF programs. 1.056883406s      
  🍕 Attached ssl eBPF programs. 3.108602644s       
  🥪 Attached conntrack eBPF programs. 78.384725ms  
  🍹 All programs attached 125.025µs                
  🍭 Waiting for events.. 184.824µs                 
                                                    
Caught panic:

!

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
        /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
        /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/runtime/debug/stack.go:18 +0x13
github.com/charmbracelet/bubbletea.(*Program).recoverFromPanic(0xc00037a000)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.2/tea.go:705 +0x8b
panic({0x12896c0?, 0x17db440?})
        /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.3.linux-amd64/src/runtime/panic.go:785 +0x132
kyanos/agent/render/watch.(*model).Update(0xc000dd2008, {0x1430e40, 0xc0004d9b30})
        /home/runner/work/kyanos/kyanos/agent/render/watch/watch_render.go:392 +0xeb8
github.com/charmbracelet/bubbletea.(*Program).eventLoop(0xc00037a000, {0x17ecf30?, 0xc000dd2008?}, 0xc000ddc070)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.2/tea.go:461 +0x810
github.com/charmbracelet/bubbletea.(*Program).Run(0xc00037a000)
        /home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v1.2.2/tea.go:595 +0xaad
kyanos/agent/render/watch.RunWatchRender({0x17f2c38, 0xc0004a2580}, 0xc00043e150, {0x0, 0x0, {0x0, 0x0}, 0x0, 0x400, 0x64})
        /home/runner/work/kyanos/kyanos/agent/render/watch/watch_render.go:580 +0x24c
kyanos/agent.SetupAgent({0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, {0x0, ...}, ...})
        /home/runner/work/kyanos/kyanos/agent/agent.go:145 +0x832
kyanos/cmd.startAgent()
        /home/runner/work/kyanos/kyanos/cmd/common.go:99 +0x5dd
kyanos/cmd.init.func10(0x2186420, {0x14f5323?, 0x4?, 0x14f51c3?})
        /home/runner/work/kyanos/kyanos/cmd/watch.go:30 +0x165
github.com/spf13/cobra.(*Command).execute(0x2186420, {0xc0000522e0, 0x1, 0x1})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xa91
github.com/spf13/cobra.(*Command).ExecuteC(0x2185e60)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
kyanos/cmd.Execute()
        /home/runner/work/kyanos/kyanos/cmd/root.go:114 +0x1a
main.main()
        /home/runner/work/kyanos/kyanos/main.go:6 +0xf
```

**Comment by hengyoush** [comment]
Thank you for you feedback, this is a bug due to specify a subcommand currently not supported(currently only support http/mysql/redis subcommand), this bug will be fixed in next release. If you are interesting, feel free to submit a pr.

**Comment by 760985933** [comment]
您好，我已收到您发送的邮件，等待我查看内容后给您回复。
